updated config.

diff --git a/config b/config
--- a/config
+++ b/config
@@ -10,26 +10,36 @@ base_dir=/home/cumulus/BootcampAutomation
 
 logfile="$base_dir/configure_servers.log"
 
+if [ "$(whoami)" != "cumulus" ]; then
+    echo " WARN: This script is supposed to be executed as the 'cumulus' user."
+fi
+
+if [ "$(pwd)" != "$base_dir" ]; then
+    echo " INFO: Changing into $base_dir..."
+    cd $base_dir
+fi
+
 if [ "$target" != "server" ]; then
-    echo "    target must be 'server' ex. 'config server lab3'"
+    echo " ERROR: target must be 'server' ex. 'config server lab3'"
     exit 1
 fi
 
 if [ "${lab:0:3}" != "lab" ]; then
-    echo "    must configure a lab. ex. 'config server lab3'"
+    echo " ERROR: must configure a lab. ex. 'config server lab3'"
     exit 1
 fi
 
 if ! [[ "$lab_number" =~ ^[1-9]$ ]]; then
-    echo "    must be a lab 1 through 9. ex. 'config server lab3'"
+    echo " ERROR: must be a lab 1 through 9. ex. 'config server lab3'"
     exit 1
 fi
 
-if ! [[ "$lab_letter" =~ ^[a-b]$ ]]; then
-    echo "    if using a letter, must be 'a' through 'b'. ex. 'config server lab4a'"
-    exit 1
+if [ "$lab_letter" != "" ]; then 
+    if ! [[ "$lab_letter" =~ ^[a-b]$ ]]; then
+        echo " ERROR: if using a letter, must be 'a' through 'b'. ex. 'config server lab4a'"
+        exit 1
+    fi
 fi
-
 
 echo "### Starting execution @ $(date +'%F %r') ###" > $logfile
 echo "        running: \"/usr/local/bin/ansible-playbook $base_dir/$lab.yml -l $target \" " > $logfile
